
package it.bmed.arch.uploadMulticanale.be.livecycle.ws.client;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Dispatcher", targetNamespace = "http://dispatcher.cedacrinternational.md/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dispatcher {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "LookupAnagraficaCedacri")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LookupAnagraficaCedacri", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LookupAnagraficaCedacri")
    @ResponseWrapper(localName = "LookupAnagraficaCedacriResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LookupAnagraficaCedacriResponse")
    public String lookupAnagraficaCedacri(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneratePDF")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GeneratePDF", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GeneratePDF")
    @ResponseWrapper(localName = "GeneratePDFResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GeneratePDFResponse")
    public byte[] generatePDF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param documentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentDeliveryFlag", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentDeliveryFlag")
    @ResponseWrapper(localName = "getDocumentDeliveryFlagResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentDeliveryFlagResponse")
    public String getDocumentDeliveryFlag(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GenerateDocumentPreview")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GenerateDocumentPreview", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GenerateDocumentPreview")
    @ResponseWrapper(localName = "GenerateDocumentPreviewResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GenerateDocumentPreviewResponse")
    public byte[] generateDocumentPreview(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetQueueIDByDepartment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetQueueIDByDepartment", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueIDByDepartment")
    @ResponseWrapper(localName = "GetQueueIDByDepartmentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueIDByDepartmentResponse")
    public int getQueueIDByDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "UpdateOrderAttachments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateOrderAttachments", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateOrderAttachments")
    @ResponseWrapper(localName = "UpdateOrderAttachmentsResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateOrderAttachmentsResponse")
    public UimResultSet updateOrderAttachments(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<BigInteger> arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "RejectDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RejectDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RejectDocument")
    @ResponseWrapper(localName = "RejectDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RejectDocumentResponse")
    public UimResultSet rejectDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        BigInteger arg3);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "DocumentAddAttachment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DocumentAddAttachment", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.DocumentAddAttachment")
    @ResponseWrapper(localName = "DocumentAddAttachmentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.DocumentAddAttachmentResponse")
    public UimResultSet documentAddAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePDFDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdatePDFDocument")
    @ResponseWrapper(localName = "updatePDFDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdatePDFDocumentResponse")
    public UimResultSet updatePDFDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "ApproveDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ApproveDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.ApproveDocument")
    @ResponseWrapper(localName = "ApproveDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.ApproveDocumentResponse")
    public UimResultSet approveDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        BigInteger arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GeneratePDFDynamic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GeneratePDFDynamic", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GeneratePDFDynamic")
    @ResponseWrapper(localName = "GeneratePDFDynamicResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GeneratePDFDynamicResponse")
    public byte[] generatePDFDynamic(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimForm>
     * @throws RepositoryException_Exception
     */
    @WebMethod(operationName = "GetDepartmentFormList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDepartmentFormList", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDepartmentFormList")
    @ResponseWrapper(localName = "GetDepartmentFormListResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDepartmentFormListResponse")
    public List<UimForm> getDepartmentFormList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimDocument>
     */
    @WebMethod(operationName = "GetQueueDocuments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetQueueDocuments", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueDocuments")
    @ResponseWrapper(localName = "GetQueueDocumentsResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueDocumentsResponse")
    public List<UimDocument> getQueueDocuments(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Long arg4);

    /**
     * 
     * @param codiceClient
     * @param rapporto
     * @param codiceDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LookupCanaliAnagrafe")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LookupCanaliAnagrafe", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LookupCanaliAnagrafe")
    @ResponseWrapper(localName = "LookupCanaliAnagrafeResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LookupCanaliAnagrafeResponse")
    public String lookupCanaliAnagrafe(
        @WebParam(name = "Rapporto", targetNamespace = "")
        String rapporto,
        @WebParam(name = "CodiceClient", targetNamespace = "")
        String codiceClient,
        @WebParam(name = "CodiceDocumento", targetNamespace = "")
        String codiceDocumento);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "SendDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.SendDocument")
    @ResponseWrapper(localName = "SendDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.SendDocumentResponse")
    public UimResultSet sendDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "AddDocumentHistoryEntry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddDocumentHistoryEntry", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AddDocumentHistoryEntry")
    @ResponseWrapper(localName = "AddDocumentHistoryEntryResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AddDocumentHistoryEntryResponse")
    public UimResultSet addDocumentHistoryEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQueuesByDepartment", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueuesByDepartment")
    @ResponseWrapper(localName = "getQueuesByDepartmentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueuesByDepartmentResponse")
    public List<Object> getQueuesByDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllModels", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetAllModels")
    @ResponseWrapper(localName = "getAllModelsResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetAllModelsResponse")
    public List<Object> getAllModels(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDocumentBatchId", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateDocumentBatchId")
    @ResponseWrapper(localName = "updateDocumentBatchIdResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateDocumentBatchIdResponse")
    public UimResultSet updateDocumentBatchId(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "CleanApprove")
    @RequestWrapper(localName = "CleanApprove", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CleanApprove")
    @ResponseWrapper(localName = "CleanApproveResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CleanApproveResponse")
    public void cleanApprove(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0);

    /**
     * 
     * @param documentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentStatus", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentStatus")
    @ResponseWrapper(localName = "getDocumentStatusResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentStatusResponse")
    public String getDocumentStatus(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimDocument
     */
    @WebMethod(operationName = "GetDocumentUIM")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentUIM", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentUIM")
    @ResponseWrapper(localName = "GetDocumentUIMResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentUIMResponse")
    public UimDocument getDocumentUIM(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "DocumentRemoveAttachment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DocumentRemoveAttachment", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.DocumentRemoveAttachment")
    @ResponseWrapper(localName = "DocumentRemoveAttachmentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.DocumentRemoveAttachmentResponse")
    public UimResultSet documentRemoveAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BigInteger arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param documentID
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lockDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LockDocument")
    @ResponseWrapper(localName = "lockDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.LockDocumentResponse")
    public int lockDocument(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SubmitXml")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SubmitXml", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.SubmitXml")
    @ResponseWrapper(localName = "SubmitXmlResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.SubmitXmlResponse")
    public int submitXml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param documentID
     * @param fileName
     * @param docAttachment
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "attachmentConversion", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AttachmentConversion")
    @ResponseWrapper(localName = "attachmentConversionResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AttachmentConversionResponse")
    public byte[] attachmentConversion(
        @WebParam(name = "FileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "docAttachment", targetNamespace = "")
        byte[] docAttachment,
        @WebParam(name = "documentID", targetNamespace = "")
        BigInteger documentID);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "RestoreDocumentFromBin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RestoreDocumentFromBin", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RestoreDocumentFromBin")
    @ResponseWrapper(localName = "RestoreDocumentFromBinResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RestoreDocumentFromBinResponse")
    public UimResultSet restoreDocumentFromBin(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "MoveDocumentToQueueType")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MoveDocumentToQueueType", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.MoveDocumentToQueueType")
    @ResponseWrapper(localName = "MoveDocumentToQueueTypeResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.MoveDocumentToQueueTypeResponse")
    public UimResultSet moveDocumentToQueueType(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "EmptyRecycleBinByUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EmptyRecycleBinByUser", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.EmptyRecycleBinByUser")
    @ResponseWrapper(localName = "EmptyRecycleBinByUserResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.EmptyRecycleBinByUserResponse")
    public UimResultSet emptyRecycleBinByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimUser
     */
    @WebMethod(operationName = "Authenticate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AuthenticateResponse")
    public UimUser authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param documentID
     * @param resultSet
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetDocumentPDF")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentPDF", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentPDF")
    @ResponseWrapper(localName = "GetDocumentPDFResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentPDFResponse")
    public byte[] getDocumentPDF(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID,
        @WebParam(name = "resultSet", targetNamespace = "")
        UimResultSet resultSet);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDepartments", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetAllDepartments")
    @ResponseWrapper(localName = "getAllDepartmentsResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetAllDepartmentsResponse")
    public List<Object> getAllDepartments(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param documentID
     * @param clientSend
     */
    @WebMethod
    @RequestWrapper(localName = "unlockDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UnlockDocument")
    @ResponseWrapper(localName = "unlockDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UnlockDocumentResponse")
    public void unlockDocument(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID,
        @WebParam(name = "ClientSend", targetNamespace = "")
        BigInteger clientSend);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimAttachment>
     */
    @WebMethod(operationName = "GetDocumentAttachments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentAttachments", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentAttachments")
    @ResponseWrapper(localName = "GetDocumentAttachmentsResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentAttachmentsResponse")
    public List<UimAttachment> getDocumentAttachments(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "MoveDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MoveDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.MoveDocument")
    @ResponseWrapper(localName = "MoveDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.MoveDocumentResponse")
    public UimResultSet moveDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        BigInteger arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param documentID
     * @param deliveryFlag
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDocumentDeliveryFlag", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AddDocumentDeliveryFlag")
    @ResponseWrapper(localName = "addDocumentDeliveryFlagResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.AddDocumentDeliveryFlagResponse")
    public UimResultSet addDocumentDeliveryFlag(
        @WebParam(name = "DocumentID", targetNamespace = "")
        BigInteger documentID,
        @WebParam(name = "DeliveryFlag", targetNamespace = "")
        String deliveryFlag);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg15
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ricercaDocumenti", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RicercaDocumenti")
    @ResponseWrapper(localName = "ricercaDocumentiResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RicercaDocumentiResponse")
    public List<Object> ricercaDocumenti(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        XMLGregorianCalendar arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        XMLGregorianCalendar arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        Long arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        Long arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        List<String> arg15);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RenderForm")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RenderForm", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RenderForm")
    @ResponseWrapper(localName = "RenderFormResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.RenderFormResponse")
    public String renderForm(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDepartment", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetUsersByDepartment")
    @ResponseWrapper(localName = "getUsersByDepartmentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetUsersByDepartmentResponse")
    public List<Object> getUsersByDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg13
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "CreateNewDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateNewDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CreateNewDocument")
    @ResponseWrapper(localName = "CreateNewDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CreateNewDocumentResponse")
    public BigInteger createNewDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        byte[] arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPdf", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CheckPdf")
    @ResponseWrapper(localName = "checkPdfResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.CheckPdfResponse")
    public UimResultSet checkPdf(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimHistory>
     */
    @WebMethod(operationName = "GetDocumentHistory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentHistory", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentHistory")
    @ResponseWrapper(localName = "GetDocumentHistoryResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetDocumentHistoryResponse")
    public List<UimHistory> getDocumentHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimDocument>
     */
    @WebMethod(operationName = "GetQueueDocumentsM2SC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetQueueDocumentsM2SC", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueDocumentsM2SC")
    @ResponseWrapper(localName = "GetQueueDocumentsM2SCResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.GetQueueDocumentsM2SCResponse")
    public List<UimDocument> getQueueDocumentsM2SC(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UimResultSet
     */
    @WebMethod(operationName = "UpdateDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateDocument", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateDocument")
    @ResponseWrapper(localName = "UpdateDocumentResponse", targetNamespace = "http://dispatcher.cedacrinternational.md/", className = "it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.UpdateDocumentResponse")
    public UimResultSet updateDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        BigInteger arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

}
