
package it.bmed.arch.uploadMulticanale.be.livecycle.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Dispatcher.3.09.19f", targetNamespace = "http://www.springframework.org/schema/beans", wsdlLocation = "/wsdl/lc.wsdl")
public class Dispatcher30919F
    extends Service
{

    private final static URL DISPATCHER30919F_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.Dispatcher30919F.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.bmed.arch.uploadMulticanale.be.livecycle.ws.client.Dispatcher30919F.class.getResource(".");
            url = new URL(baseUrl, "/wsdl/lc.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/wsdl/lc.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DISPATCHER30919F_WSDL_LOCATION = url;
    }

    public Dispatcher30919F(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dispatcher30919F() {
        super(DISPATCHER30919F_WSDL_LOCATION, new QName("http://www.springframework.org/schema/beans", "Dispatcher.3.09.19f"));
    }

    /**
     * 
     * @return
     *     returns Dispatcher
     */
    @WebEndpoint(name = "DispatcherImplPort")
    public Dispatcher getDispatcherImplPort() {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "DispatcherImplPort"), Dispatcher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dispatcher
     */
    @WebEndpoint(name = "DispatcherImplPort")
    public Dispatcher getDispatcherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "DispatcherImplPort"), Dispatcher.class, features);
    }

}
