
package it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "onboarding-exception", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding/model")
public class OnboardingException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Error faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public OnboardingException(String message, Error faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public OnboardingException(String message, Error faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.Error
     */
    public Error getFaultInfo() {
        return faultInfo;
    }

}
