
package it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OnboardingService", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnboardingService {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.AddDocumentsExResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "addDocumentsEx")
    @WebResult(name = "addDocumentsExResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    AddDocumentsExResponse addDocumentsEx(
        @WebParam(name = "addDocumentsEx", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        AddDocumentsEx parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.GetNewTokenResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "getNewToken")
    @WebResult(name = "getNewTokenResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    GetNewTokenResponse getNewToken(
        @WebParam(name = "getNewToken", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        GetNewToken parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.AddDocumentsResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "addDocuments")
    @WebResult(name = "addDocumentsResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    AddDocumentsResponse addDocuments(
        @WebParam(name = "addDocuments", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        AddDocuments parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.GetDossierResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "getDossier")
    @WebResult(name = "getDossierResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    GetDossierResponse getDossier(
        @WebParam(name = "getDossier", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        GetDossier parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.GetWebidServiceInfoResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "getWebidServiceInfo")
    @WebResult(name = "getWebidServiceInfoResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    GetWebidServiceInfoResponse getWebidServiceInfo(
        @WebParam(name = "getWebidServiceInfo", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        GetWebidServiceInfo parameters)
        throws OnboardingException
    ;

    /**@WebServiceClient
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.GetDossierStatusResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "getDossierStatus")
    @WebResult(name = "getDossierStatusResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    GetDossierStatusResponse getDossierStatus(
        @WebParam(name = "getDossierStatus", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        GetDossierStatus parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.CadesSignResponse
     */
    @WebMethod(action = "cadesSign")
    @WebResult(name = "cadesSignResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    CadesSignResponse cadesSign(
        @WebParam(name = "cadesSign", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        CadesSign parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.CreateDossierResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "createDossier")
    @WebResult(name = "createDossierResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    CreateDossierResponse createDossier(
        @WebParam(name = "createDossier", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        CreateDossier parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.AssertIdentityResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "assertIdentity")
    @WebResult(name = "assertIdentityResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    AssertIdentityResponse assertIdentity(
        @WebParam(name = "assertIdentity", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        AssertIdentity parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.AssertAuthorizationResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "assertAuthorization")
    @WebResult(name = "assertAuthorizationResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    AssertAuthorizationResponse assertAuthorization(
        @WebParam(name = "assertAuthorization", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        AssertAuthorization parameters)
        throws OnboardingException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns it.bmed.arch.uploadMulticanale.be.service.onboarding.wsclient.GetDossiersByBusinessIdResponse
     * @throws OnboardingException
     */
    @WebMethod(action = "getDossiersByBusinessId")
    @WebResult(name = "getDossiersByBusinessIdResponse", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
    GetDossiersByBusinessIdResponse getDossiersByBusinessId(
        @WebParam(name = "getDossiersByBusinessId", targetNamespace = "http://www.infocert.it/legalbus/cop/onboarding", partName = "parameters")
        GetDossiersByBusinessId parameters)
        throws OnboardingException
    ;

}
