
package it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "firmaWS", targetNamespace = "http://firma.webservice.ncfr.infocert.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirmaWS {


    /**
     * 
     * @param pin
     * @param alias
     * @param documentoDaFirmare
     * @param otp
     * @param dominio
     * @return
     *     returns java.lang.String
     * @throws FirmaWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "firmaCADES", targetNamespace = "http://firma.webservice.ncfr.infocert.it/", className = "it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaCADES")
    @ResponseWrapper(localName = "firmaCADESResponse", targetNamespace = "http://firma.webservice.ncfr.infocert.it/", className = "it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaCADESResponse")
    public String firmaCADES(
        @WebParam(name = "documentoDaFirmare", targetNamespace = "")
        String documentoDaFirmare,
        @WebParam(name = "dominio", targetNamespace = "")
        String dominio,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "pin", targetNamespace = "")
        String pin,
        @WebParam(name = "otp", targetNamespace = "")
        String otp)
        throws FirmaWSException_Exception
    ;

    /**
     * 
     * @param firmatari
     * @param documentoDaFirmare
     * @return
     *     returns java.lang.String
     * @throws FirmaWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "firmaPADES", targetNamespace = "http://firma.webservice.ncfr.infocert.it/", className = "it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaPADES")
    @ResponseWrapper(localName = "firmaPADESResponse", targetNamespace = "http://firma.webservice.ncfr.infocert.it/", className = "it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaPADESResponse")
    public String firmaPADES(
        @WebParam(name = "documentoDaFirmare", targetNamespace = "")
        String documentoDaFirmare,
        @WebParam(name = "firmatari", targetNamespace = "")
        String firmatari)
        throws FirmaWSException_Exception
    ;

}
