
package it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "firmaWSService", targetNamespace = "http://firma.webservice.ncfr.infocert.it/", wsdlLocation = "/wsdl/infocerta.wsdl")
public class FirmaWSService
    extends Service
{

    private final static URL FIRMAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRMAWSSERVICE_EXCEPTION;
    private final static QName FIRMAWSSERVICE_QNAME = new QName("http://firma.webservice.ncfr.infocert.it/", "firmaWSService");

    static {
        FIRMAWSSERVICE_WSDL_LOCATION = it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaWSService.class.getResource("/wsdl/infocerta.wsdl");
        WebServiceException e = null;
        if (FIRMAWSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/infocerta.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        FIRMAWSSERVICE_EXCEPTION = e;
    }

    public FirmaWSService() {
        super(__getWsdlLocation(), FIRMAWSSERVICE_QNAME);
    }

    public FirmaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FirmaWS
     */
    @WebEndpoint(name = "firmaWSPort")
    public FirmaWS getFirmaWSPort() {
        return super.getPort(new QName("http://firma.webservice.ncfr.infocert.it/", "firmaWSPort"), FirmaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaWS
     */
    @WebEndpoint(name = "firmaWSPort")
    public FirmaWS getFirmaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://firma.webservice.ncfr.infocert.it/", "firmaWSPort"), FirmaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRMAWSSERVICE_EXCEPTION!= null) {
            throw FIRMAWSSERVICE_EXCEPTION;
        }
        return FIRMAWSSERVICE_WSDL_LOCATION;
    }

}
