
package it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "FirmaWSException", targetNamespace = "http://firma.webservice.ncfr.infocert.it/")
public class FirmaWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FirmaWSException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FirmaWSException_Exception(String message, FirmaWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FirmaWSException_Exception(String message, FirmaWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.bmed.ib.uploadmulticanale.file.be.wsclient.sign.infocert.FirmaWSException
     */
    public FirmaWSException getFaultInfo() {
        return faultInfo;
    }

}
